catalogs:
  build:
    vite: ^7.1.3
    vitepress: 2.0.0-alpha.12
    vitepress-plugin-group-icons: ^1.6.3
  cli:
    pncat: ^0.5.1
  dev:
    '@antfu/ni': ^25.0.0
    '@xiaohe01/tsconfig': ^2.0.0
    typescript: ~5.8.3
  frontend:
    '@vue/runtime-core': ^3.5.20
    vue: ^3.5.20
    vue-tsc: ^3.0.6
  icons:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/tabler': ^1.2.22
  lint:
    '@xiaohe01/eslint-config': ^2.2.1
    '@xiaohe01/stylelint-config': ^2.4.0
    eslint: ^9.34.0
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.13.1
    stylelint: ^16.23.1
  prod:
    await-to-js: ^3.0.0
    es-toolkit: ^1.39.10
  script:
    esno: ^4.8.0
  style:
    unocss: ^66.4.2
  utils:
    '@vueuse/core': ^13.8.0
    dayjs: ^1.11.15
onlyBuiltDependencies:
  - esbuild
  - pncat
  - simple-git-hooks