catalogMode: prefer
shellEmulator: true

catalogs:
  build:
    vite: ^7.2.7
  cli:
    "@antfu/ni": ^28.0.0
    pncat: ^0.7.7
  dev:
    "@vue/runtime-core": ^3.5.25
  docs:
    vitepress: 2.0.0-alpha.12
    vitepress-plugin-group-icons: ^1.6.5
  frontend:
    vue: ^3.5.25
  icons:
    "@iconify-json/carbon": ^1.2.15
    "@iconify-json/tabler": ^1.2.23
  lint:
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    stylelint: ^16.26.1
  script:
    esno: ^4.8.0
  style:
    unocss: ^66.5.10
  tsc:
    typescript: ~5.9.3
    vue-tsc: ^3.1.8
  types:
    "@types/node": ^22.19.3
  utils:
    "@vueuse/core": ^14.1.0
    await-to-js: ^3.0.0
    dayjs: ^1.11.19
    es-toolkit: ^1.43.0
  xiaohe:
    "@xiaohe01/eslint-config": ^4.1.0
    "@xiaohe01/stylelint-config": ^3.1.0
    "@xiaohe01/tsconfig": ^3.1.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks