catalogs:
  build:
    vite: ^7.2.2
  cli:
    "@antfu/ni": ^27.0.1
    pncat: ^0.7.6
  dev:
    "@vue/runtime-core": ^3.5.24
  docs:
    vitepress: 2.0.0-alpha.12
    vitepress-plugin-group-icons: ^1.6.5
  frontend:
    vue: ^3.5.24
  icons:
    "@iconify-json/carbon": ^1.2.14
    "@iconify-json/tabler": ^1.2.23
  lint:
    eslint: ^9.39.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    stylelint: ^16.25.0
  script:
    esno: ^4.8.0
  style:
    unocss: ^66.5.7
  tsc:
    typescript: ~5.9.3
    vue-tsc: ^3.1.4
  types:
    "@types/node": ^22.19.1
  utils:
    "@vueuse/core": ^14.0.0
    await-to-js: ^3.0.0
    dayjs: ^1.11.19
    es-toolkit: ^1.42.0
  xiaohe:
    "@xiaohe01/eslint-config": ^4.0.0
    "@xiaohe01/stylelint-config": ^3.0.0
    "@xiaohe01/tsconfig": ^3.0.0
onlyBuiltDependencies:
  - esbuild
  - pncat
  - simple-git-hooks